spring.application.name=config
server.port=8888

spring.cloud.config.server.git.uri= https://github.com/spring-cloud-samples/config-repo

# spring.cloud.config.server.git.uri=D:\stsWorkspace\cld02\config\config

# spring.profiles.active=native
# spring.cloud.config.server.native.search-locations=file://D:\stsWorkspace\cld02\config\config

# spring.cloud.config.server.git.uri= file://D:\stsWorkspace\cld02\config\config
# spring.cloud.config.server.git.default-label=master

logging.level.web=debug
logging.level.com.sts=debug