services:
  # servicee:
    # image: servicee
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile
    # ports:
    #   - 7011:7011

  mysql:
    image: mysql:lts
    restart: always
    # build:
    #   context: contextPath
    #   dockerfile: Dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: xe
    volumes:
      - db8:/var/lib/mysql
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  db8:
   driver: local
