spring.application.name=sts28

spring.data.mongodb.authentication-database=admin
spring.data.mongodb.host=localhost
spring.data.mongodb.username=root
spring.data.mongodb.password=mongo
spring.data.mongodb.port=27017
spring.data.mongodb.database=blog