spring.application.name=userapi

server.port=8092

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:./db/data
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2

logging.level.web= debug
logging.level.com.sts=debug

spring.data.redis.host=localhost
spring.data.redis.port=6379